package com.example.ai

import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import java.util.concurrent.TimeUnit

sealed class AiResult<out T> {
    data class Success<T>(val data: T) : AiResult<T>()
    data class Error(val message: String) : AiResult<Nothing>()
}

class AiAssistRepository {

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val moshi = Moshi.Builder()
        .add(KotlinJsonAdapterFactory())
        .build()

    private val requestAdapter = moshi.adapter(GenerateContentRequest::class.java)
    private val responseAdapter = moshi.adapter(GenerateContentResponse::class.java)

    private fun getApiKey(): String {
        return try {
            BuildConfig.GEMINI_API_KEY
        } catch (e: Throwable) {
            ""
        }
    }

    private suspend fun callGeminiApi(
        systemPrompt: String,
        userPrompt: String
    ): AiResult<String> = withContext(Dispatchers.IO) {
        val apiKey = getApiKey()
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext AiResult.Error(
                "Gemini API key is missing or not configured. Add your key in the AI Studio Secrets panel."
            )
        }

        val requestData = GenerateContentRequest(
            contents = listOf(
                Content(
                    parts = listOf(Part(text = userPrompt)),
                    role = "user"
                )
            ),
            generationConfig = GenerationConfig(temperature = 0.3f),
            systemInstruction = Content(
                parts = listOf(Part(text = systemPrompt))
            )
        )

        val jsonBody = requestAdapter.toJson(requestData)
        val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"

        val request = Request.Builder()
            .url(url)
            .post(jsonBody.toRequestBody("application/json".toMediaType()))
            .build()

        try {
            val response = client.newCall(request).execute()
            val bodyString = response.body?.string() ?: ""

            if (!response.isSuccessful) {
                return@withContext AiResult.Error("API call failed (${response.code}): $bodyString")
            }

            val parsedResponse = responseAdapter.fromJson(bodyString)
            val outputText = parsedResponse?.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text

            if (outputText != null) {
                AiResult.Success(outputText.trim())
            } else {
                val errMessage = parsedResponse?.error?.message ?: "No response generated by model."
                AiResult.Error(errMessage)
            }
        } catch (e: Exception) {
            AiResult.Error("Network error: ${e.localizedMessage ?: "Unknown error"}")
        }
    }

    suspend fun getInlineCompletion(
        codeBeforeCursor: String,
        codeAfterCursor: String,
        language: String
    ): AiResult<String> {
        val systemPrompt = "You are an expert AI code auto-completer for $language in VS Code Mobile IDE. Output ONLY the inline code completion snippet that should directly follow the cursor. Do not include markdown ticks, conversational text, or explanations."
        val userPrompt = "Code before cursor:\n```$language\n$codeBeforeCursor\n```\nCode after cursor:\n```$language\n$codeAfterCursor\n```\nProvide ONLY the code snippet completion:"
        
        val result = callGeminiApi(systemPrompt, userPrompt)
        if (result is AiResult.Error) {
            // Provide intelligent local heuristic fallback if API key is missing
            val fallback = HeuristicCodeCompleter.suggest(codeBeforeCursor, language)
            return AiResult.Success(fallback)
        }
        return result
    }

    suspend fun explainCode(codeSnippet: String, language: String): AiResult<String> {
        val systemPrompt = "You are a code tutor inside a mobile IDE. Provide a clear, structured explanation of the provided $language code block. Use markdown formatting with bullet points and key concepts."
        val userPrompt = "Explain this $language code:\n```$language\n$codeSnippet\n```"
        return callGeminiApi(systemPrompt, userPrompt)
    }

    suspend fun detectBugs(codeSnippet: String, language: String): AiResult<String> {
        val systemPrompt = "You are a static analysis tool and bug finder for $language. Scan the given code for syntax errors, logical bugs, security risks, or memory leaks. Return a formatted report with line issues and recommended fixes."
        val userPrompt = "Analyze this $language code for bugs:\n```$language\n$codeSnippet\n```"
        return callGeminiApi(systemPrompt, userPrompt)
    }

    suspend fun suggestRefactoring(codeSnippet: String, language: String): AiResult<String> {
        val systemPrompt = "You are a senior software architect specializing in $language. Suggest clean code refactorings, performance enhancements, and modern syntax improvements for the code snippet."
        val userPrompt = "Suggest refactorings for this $language code:\n```$language\n$codeSnippet\n```"
        return callGeminiApi(systemPrompt, userPrompt)
    }

    suspend fun generateDocstrings(codeSnippet: String, language: String): AiResult<String> {
        val systemPrompt = if (language == "py" || language == "python") {
            "You are a Python docstring generator adhering to PEP 257 standard. Output ONLY the code with docstrings attached."
        } else {
            "You are a documentation generator for $language. Output ONLY the code with comprehensive documentation comments added."
        }
        val userPrompt = "Generate documentation comments for this code:\n```$language\n$codeSnippet\n```"
        return callGeminiApi(systemPrompt, userPrompt)
    }

    suspend fun generateUnitTests(codeSnippet: String, language: String): AiResult<String> {
        val testFramework = if (language == "py" || language == "python") "unittest / pytest" else "Jest / Mocha"
        val systemPrompt = "You are an automated testing generator specializing in $testFramework for $language. Generate comprehensive unit tests covering edge cases and main functionality."
        val userPrompt = "Generate complete unit tests for this $language code:\n```$language\n$codeSnippet\n```"
        return callGeminiApi(systemPrompt, userPrompt)
    }

    suspend fun chatWithAi(
        conversationHistory: List<Pair<String, String>>,
        activeCode: String,
        language: String
    ): AiResult<String> {
        val systemPrompt = "You are CodeStudio AI, a helpful coding assistant built directly into the VS Code Mobile IDE. You have context on the user's active $language file. Be concise, developer-friendly, and provide complete runnable code snippets when asked."
        val historyFormatted = conversationHistory.joinToString("\n") { (role, text) ->
            "$role: $text"
        }
        val userPrompt = "Active File ($language):\n```$language\n$activeCode\n```\n\nConversation History:\n$historyFormatted\n\nPlease answer the user's latest query."
        return callGeminiApi(systemPrompt, userPrompt)
    }
}

/**
 * Intelligent local fallback completion generator when Gemini API key is offline/unset.
 */
object HeuristicCodeCompleter {
    fun suggest(codeBeforeCursor: String, language: String): String {
        val line = codeBeforeCursor.lines().lastOrNull()?.trim() ?: ""
        return when {
            language.lowercase() in listOf("py", "python") -> {
                when {
                    line.startsWith("def ") -> " (self):\n    \"\"\"Docstring\"\"\"\n    pass"
                    line.startsWith("if ") -> " __name__ == '__main__':\n    main()"
                    line.startsWith("for ") -> " i in range(10):\n    print(i)"
                    line.startsWith("import ") -> " math, os, sys"
                    line.startsWith("print") -> "(\"Hello from Python!\")"
                    else -> "  # TODO: Implement logic"
                }
            }
            language.lowercase() in listOf("html", "xml") -> {
                when {
                    line.startsWith("<div") -> " class=\"container\">\n    <p>Content</p>\n</div>"
                    line.startsWith("<button") -> " class=\"btn\" onclick=\"handleClick()\">Submit</button>"
                    line.startsWith("<script") -> ">\n    console.log('Ready');\n</script>"
                    line.startsWith("<style") -> ">\n    body { font-family: sans-serif; }\n</style>"
                    else -> "><p>Sample HTML block</p></div>"
                }
            }
            else -> " // AI Code Completion"
        }
    }
}
